[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Oskar Wiszowty <ppwiszu@gmail.com>"]
edition = "2024"

[lib]
path = "src/lib.rs"
name = "zero2prod"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
reqwest = "0.12"
